### GetAll
GET http://localhost:5000/films


### GetFilmByID
GET http://localhost:5000/films/1


### CreateFilm
POST http://localhost:5000/films HTTP/1.1
content-type: application/json

{
    "title" = "Uma squad do barulho"
    "rate" = 5
    "synopsis" = "5 programadores muito dos focados fazendo de tudo pra codar com qualidade"
    "poster_url" = "https://imgur.com/download/BgiTRRG/"
    "main_cast" = [
        "Miguel",
        "Gabriel",
        "Alexia",
        "Carolina",
        "Olga"
    ]
}


### DeleteFilmByID
DELETE  http://localhost:5000/films/1


### ChangeFilmByID
PUT http://localhost:5000/films/1
 HTTP/1.1
content-type: application/json

{
    "var": "content",
    "var": "content"
}